version: '3'

services:

  backend:
    build: ./backend
    container_name: boilerplate-backend
    ports:
      - 7337:7337


  frontend:
    build: ./frontend
    container_name: boilerplate-frontend
    ports:
      - 3000:3000
    links: 
      - backend